version : '3'

services: 
      redis-server: 
        image: 'redis'
      mongo-service: 
        image: 'mongo'
        ports:
        - "27017:27017"
      node-app : 
        restart: on-failure 
        build: .
        ports: 
        - "8080:8080"
        depends_on:
        - mongo-service
        - redis-server
     